# Generated by Django 2.1.4 on 2019-01-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190103_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='notes.Note')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('checklist_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='notes.Checklist')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
