# Generated by Django 2.1.4 on 2019-01-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_checklist_checklistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='note_id',
            new_name='note',
        ),
    ]
