# Generated by Django 2.1.4 on 2019-01-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190103_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='checklist_id',
            new_name='checklist',
        ),
    ]
