# Generated by Django 2.1.4 on 2019-01-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20190108_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
