# Generated by Django 2.1.4 on 2019-01-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_checklistitem_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='note',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='notes.Note'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='notes.Checklist'),
        ),
    ]
